test:
   mysql:
      host: "127.0.0.1"
      username: "root"
      password: "123456"
      port: 3306
      database: "testdb"

   redis:
      host: "127.0.0.1"
      password: "123456"
      db: 0

prod:
   mysql:
      host: "127.0.0.1"
      username: "root"
      password: "123456"
      port: 3306
      database: "testdb"

   redis:
      host: "127.0.0.1"
      password: "123456"
      db: 0

dev:
   mysql:
      host: "127.0.0.1"
      username: "root"
      password: "123456"
      port: 3306
      database: "testdb"

   redis:
      host: "127.0.0.1"
      password: 123456
      db: 0

secret:
   SECRET_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
   ALGORITHM: "HS256"
   ACCESS_TOKEN_EXPIRE_MINUTES: 30
